
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JMenuItem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dorothy
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        getContentPane().setBackground(Color.BLACK);
        initComponents();
    }
    
     public JButton gETADDEMP(){
        return ADDEMP;
    }
    public JButton getADDRES(){
        return ADDRES;
    }
    public JButton getADDSUITES(){
        return ADDSUITES;
    }
    public JButton getDELETEMP(){
        return DELETEMP;
    }
    public JButton getDELETERES(){
        return DELETERES;
    }
    public JButton getDELETESUITES(){
        return DELETESUITES;
    }
    public JButton getEXPORT(){
        return EXPORT;
    }
    public JButton getIMPORT(){
        return IMPORT;
    }
    public JButton getLISTALL(){
        return LISTALL;
    }
    public JButton getLISTEMP(){
        return LISTEMP;
    }
    public JButton getLISTRES(){
        return LISTRES;
    }
    public JButton getLISTSUITE(){
        return LISTSUITE;
    }
    public JButton getMODIFYEMP(){
        return MODIFYEMP;
    }
    public JButton getMODIFYRES(){
        return MODIFYRES;
    }
    public JButton getSEARCH(){
        return SEARCH;
    }
    
    
    public JMenuItem getADDBOOKINGMENU(){
    return ADDBOOKINGMENU;
    }
    public JMenuItem getDELETEBOOKINGMENU(){
    return DELETEBOOKINGMENU;
    }
    public JMenuItem getADDROOMMENU(){
    return ADDROOMMENU;
    }
    public JMenuItem getDELETEEMPMENU(){
    return DELETEEMPMENU;
    }
    public JMenuItem getDELETEROOMMENU(){
    return DELETEROOMMENU;
    }
    public JMenuItem getEDITBOOKINGMENU(){
    return EDITBOOKINGMENU;
    }
    public JMenuItem getEDITEMPMENU(){
    return EDITEMPMENU;
    }
    public JMenuItem getLISTBOOKINGMENU(){
    return LISTBOOKINGMENU;
    }
    public JMenuItem getLISTEMPMENU(){
    return LISTEMPMENU;
    }
    public JMenuItem getLISTROOMMENU(){
    return LISTROOMMENU;
    }
    public JMenuItem getADDING(){
    return ADDING;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ADDEMP = new javax.swing.JButton();
        MODIFYEMP = new javax.swing.JButton();
        DELETEMP = new javax.swing.JButton();
        LISTEMP = new javax.swing.JButton();
        ADDSUITES = new javax.swing.JButton();
        DELETESUITES = new javax.swing.JButton();
        LISTSUITE = new javax.swing.JButton();
        ADDRES = new javax.swing.JButton();
        MODIFYRES = new javax.swing.JButton();
        DELETERES = new javax.swing.JButton();
        LISTRES = new javax.swing.JButton();
        IMPORT = new javax.swing.JButton();
        EXPORT = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        LISTALL = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        ADDEMPMENU = new javax.swing.JMenu();
        ADDING = new javax.swing.JMenuItem();
        EDITEMPMENU = new javax.swing.JMenuItem();
        DELETEEMPMENU = new javax.swing.JMenuItem();
        LISTEMPMENU = new javax.swing.JMenuItem();
        SUITEMENU = new javax.swing.JMenu();
        ADDROOMMENU = new javax.swing.JMenuItem();
        DELETEROOMMENU = new javax.swing.JMenuItem();
        LISTROOMMENU = new javax.swing.JMenuItem();
        RESMENU = new javax.swing.JMenu();
        ADDBOOKINGMENU = new javax.swing.JMenuItem();
        EDITBOOKINGMENU = new javax.swing.JMenuItem();
        DELETEBOOKINGMENU = new javax.swing.JMenuItem();
        LISTBOOKINGMENU = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("EMPLOYEES");

        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("SUITES");

        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("RESERVATIONS");

        ADDEMP.setText("ADD");

        MODIFYEMP.setText("MODIFY");

        DELETEMP.setText("DELETE");

        LISTEMP.setText("LIST");

        ADDSUITES.setText("ADD");

        DELETESUITES.setText("DELETE");

        LISTSUITE.setText("LIST");

        ADDRES.setText("ADD");

        MODIFYRES.setText("MODIFY");

        DELETERES.setText("DELETE");

        LISTRES.setText("LIST");

        IMPORT.setText("IMPORT");

        EXPORT.setText("EXPORT");

        SEARCH.setText("SEARCH");

        LISTALL.setText("LIST RESERVATIONS");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dorothy\\Desktop\\homepage.jpg")); // NOI18N

        ADDEMPMENU.setText("Employees");

        ADDING.setText("Add Employee");
        ADDEMPMENU.add(ADDING);

        EDITEMPMENU.setText("Edit Employee Details");
        ADDEMPMENU.add(EDITEMPMENU);

        DELETEEMPMENU.setText("Delete Employee");
        ADDEMPMENU.add(DELETEEMPMENU);

        LISTEMPMENU.setText("List Employees");
        ADDEMPMENU.add(LISTEMPMENU);

        menubar.add(ADDEMPMENU);

        SUITEMENU.setText("Rooms");

        ADDROOMMENU.setText("Add Room");
        SUITEMENU.add(ADDROOMMENU);

        DELETEROOMMENU.setText("Delete Room");
        SUITEMENU.add(DELETEROOMMENU);

        LISTROOMMENU.setText("List Rooms");
        SUITEMENU.add(LISTROOMMENU);

        menubar.add(SUITEMENU);

        RESMENU.setText("Reservations");

        ADDBOOKINGMENU.setText("Add Booking");
        RESMENU.add(ADDBOOKINGMENU);

        EDITBOOKINGMENU.setText("Edit Bookings");
        RESMENU.add(EDITBOOKINGMENU);

        DELETEBOOKINGMENU.setText("Delete Booking");
        RESMENU.add(DELETEBOOKINGMENU);

        LISTBOOKINGMENU.setText("List Bookings");
        RESMENU.add(LISTBOOKINGMENU);

        menubar.add(RESMENU);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addComponent(MODIFYEMP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ADDEMP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DELETEMP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LISTEMP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IMPORT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ADDRES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DELETERES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LISTRES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(MODIFYRES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LISTALL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SEARCH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EXPORT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LISTSUITE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DELETESUITES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ADDSUITES, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ADDSUITES)
                        .addComponent(ADDRES))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ADDEMP)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MODIFYEMP)
                            .addComponent(DELETESUITES)
                            .addComponent(MODIFYRES))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DELETERES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DELETEMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LISTSUITE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LISTRES)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LISTEMP)
                        .addComponent(EXPORT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SEARCH)
                        .addComponent(LISTALL))
                    .addComponent(IMPORT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ADDBOOKINGMENU;
    private javax.swing.JButton ADDEMP;
    private javax.swing.JMenu ADDEMPMENU;
    private javax.swing.JMenuItem ADDING;
    private javax.swing.JButton ADDRES;
    private javax.swing.JMenuItem ADDROOMMENU;
    private javax.swing.JButton ADDSUITES;
    private javax.swing.JMenuItem DELETEBOOKINGMENU;
    private javax.swing.JMenuItem DELETEEMPMENU;
    private javax.swing.JButton DELETEMP;
    private javax.swing.JButton DELETERES;
    private javax.swing.JMenuItem DELETEROOMMENU;
    private javax.swing.JButton DELETESUITES;
    private javax.swing.JMenuItem EDITBOOKINGMENU;
    private javax.swing.JMenuItem EDITEMPMENU;
    private javax.swing.JButton EXPORT;
    private javax.swing.JButton IMPORT;
    private javax.swing.JButton LISTALL;
    private javax.swing.JMenuItem LISTBOOKINGMENU;
    private javax.swing.JButton LISTEMP;
    private javax.swing.JMenuItem LISTEMPMENU;
    private javax.swing.JButton LISTRES;
    private javax.swing.JMenuItem LISTROOMMENU;
    private javax.swing.JButton LISTSUITE;
    private javax.swing.JButton MODIFYEMP;
    private javax.swing.JButton MODIFYRES;
    private javax.swing.JMenu RESMENU;
    private javax.swing.JButton SEARCH;
    private javax.swing.JMenu SUITEMENU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
